# Site settings
title: Rogue Hack Lab
description: Rogue Hack Lab is is a community of makers with roots extending throughout Southern Oregon and around the world. Join us to share, create, collaborate, research, develop, mentor, cross-pollinate, play, and of course, learn.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rogue Hack Lab
user_description: Rogue Hack Lab is is a community of makers with roots extending throughout Southern Oregon and around the world. Join us to share, create, collaborate, research, develop, mentor, cross-pollinate, play, and of course, learn.
user_title: Medford, Oregon
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "UA-50519192-2"

exclude: ['package.json', 'src' , 'node_modules']
